<template><div><h2 id="apt" tabindex="-1"><a class="header-anchor" href="#apt"><span>apt</span></a></h2>
<div class="language-dockerfile line-numbers-mode" data-highlighter="shiki" data-ext="dockerfile" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">RUN</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> echo </span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">"deb https://mirrors.ustc.edu.cn/ubuntu jammy main restricted"</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> > /etc/apt/sources.list &#x26;&#x26; \</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">    echo </span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">"deb https://mirrors.ustc.edu.cn/ubuntu jammy-updates main restricted"</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> >> /etc/apt/sources.list &#x26;&#x26; \</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">    echo </span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">"deb https://mirrors.ustc.edu.cn/ubuntu jammy universe"</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> >> /etc/apt/sources.list &#x26;&#x26; \</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">    echo </span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">"deb https://mirrors.ustc.edu.cn/ubuntu jammy-updates universe"</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> >> /etc/apt/sources.list &#x26;&#x26; \</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">    echo </span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">"deb https://mirrors.ustc.edu.cn/ubuntu jammy multiverse"</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> >> /etc/apt/sources.list &#x26;&#x26; \</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">    echo </span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">"deb https://mirrors.ustc.edu.cn/ubuntu jammy-updates multiverse"</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> >> /etc/apt/sources.list &#x26;&#x26; \</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">    echo </span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">"deb https://mirrors.ustc.edu.cn/ubuntu jammy-backports main restricted universe multiverse"</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> >> /etc/apt/sources.list &#x26;&#x26; \</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">    echo </span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">"deb https://mirrors.ustc.edu.cn/ubuntu jammy-security main restricted"</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> >> /etc/apt/sources.list &#x26;&#x26; \</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">    echo </span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">"deb https://mirrors.ustc.edu.cn/ubuntu jammy-security universe"</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> >> /etc/apt/sources.list &#x26;&#x26; \</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">    echo </span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">"deb https://mirrors.ustc.edu.cn/ubuntu jammy-security multiverse"</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> >> /etc/apt/sources.list</span></span>
<span class="line"><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">RUN</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 871920D1991BC93C</span></span>
<span class="line"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD"># RUN rm -r /etc/apt/sources.list.d</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="pip" tabindex="-1"><a class="header-anchor" href="#pip"><span>pip</span></a></h2>
<div class="language-dockerfile line-numbers-mode" data-highlighter="shiki" data-ext="dockerfile" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">RUN</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> mkdir -p /root/.pip</span></span>
<span class="line"><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">RUN</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> echo </span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">"[global]"</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> > /root/.pip/pip.conf &#x26;&#x26; \</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">    echo </span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">"index-url = https://pypi.mirrors.ustc.edu.cn/simple/"</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> >> /root/.pip/pip.conf &#x26;&#x26; \</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">    echo </span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">"[install]"</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> >> /root/.pip/pip.conf &#x26;&#x26; \</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">    echo </span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">"trusted-host=mirrors.ustc.edu.cn"</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> >> /root/.pip/pip.conf</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


