<template><div><p>参考<a href="https://github.com/orgs/community/discussions/27456" target="_blank" rel="noopener noreferrer">Authenticated but can't fetch or push</a></p>
<p>在<code v-pre>git pull</code>的时候，明明配置好了 ssh-key，但仍然报错：</p>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">git@github.com:</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> Permission</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> denied</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> (publickey).</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">fatal:</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> Could</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> not</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> read</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> from</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> remote</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> repository.</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">Please</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> make</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> sure</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> you</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> have</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> the</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> correct</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> access</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> rights</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">and</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> the</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> repository</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> exists.</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>首先使用<code v-pre>ssh -vT git@github.com</code>验证 ssh 和 public key 是不是正常的，如果返回内容中有：</p>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">Hi</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> YourUserName!</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> You</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">'</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">ve successfully authenticated, but GitHub does not provide shell access.</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>这样的内容，那说明 ssh 和 public key 配置没有问题。</p>
<p>可能导致这样问题的原因可能是 git 使用的内嵌 ssh，而这个内嵌的 ssh 找不到我们配置的 rsa 密钥。</p>
<p>解决办法就是先卸载 git，然后重新安装时注意选择<code v-pre>Use External OpenSSH</code>!</p>
<figure><img src="@source/随记/Git/extssh.png" alt="external openssh" tabindex="0" loading="lazy" width="408" height="125"><figcaption>external openssh</figcaption></figure>
</div></template>


